### ISSUE TITLE
Caught deadly signal SEGV when :PrettierAsync with large file

### ISSUE THREAD

**Issue by Luobata** [prettier/vim-prettier#128] opened 2018-04-03 06:56 UTC
The vim crash when :PrettierAsync with large file(around 500 lines after prettier).And it's fine with :Prettier.
```
:PrettierCliVersion
1.10.2^@

:PrettierCliPath
/Users/chenghaoyao/luobata/bytedance/crm_fe/node_modules/.bin/prettier

:PrettierVersion
0.2.6
```

My vim version:
```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr  3 2018 14:23:45)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit  -L/usr/local/lib -llua -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

btw: I found this problem when update my Mac OS version to 10.13.4.

**Comment by playahater** [comment] 2018-04-08 18:34
hi guys,

Same case here. i'm having this problem for a while now. using vim -u NONE when loading this file; that's the fastest fix for now :)
Think there's a low chance that there's an issue with OS or any dependency lib.

Concretely, the file is .ts with ~1700LOC .. There's all kinds of stuff in it. inline sql query lines, backticks and typescript code. Didn't have time to debug to see where it might break. Whether it is loc, specific type of line, backtick .. or none of the above.

i get `abort (core dumped)` error

I'm using VIM - Vi IMproved 8.0 on ArchLinux x86_64
When plugin is disabled, everything works just fine.

I could maybe send the file by email if needed for debugging purposes.

settings i currently use:

```
  let g:prettier#config#print_width = 170                                                                                                                                                                                                                                               
  let g:prettier#config#tab_width = 4                                                                                                                                                                                                                                                   
  let g:prettier#config#use_tabs = 'false'                                                                                                                                                                                                                                              
  let g:prettier#config#semi = 'true'                                                                                                                                                                                                                                                   
  let g:prettier#config#single_quote = 'true'                                                                                                                                                                                                                                           
  let g:prettier#config#bracket_spacing = 'true'                                                                                                                                                                                                                                        
  let g:prettier#config#jsx_bracket_same_line = 'true'                                                                                                                                                                                                                                  
  let g:prettier#config#trailing_comma = 'all'                                                                                                                                                                                                                                          
  let g:prettier#config#parser = 'typescript'                                                                                                                                                                                                                                           
  let g:prettier#config#config_precedence = 'prefer-file'
```

Feel free to ping if i can provide any more info.

cheers ..

**Comment by mitermayer** [comment] 2018-04-08 18:40
Hi @playahater,

Thank you for adding all this info, if you can paste the file on "gist" or somewhere online I will start looking into this straight away.

 Would definitly want to identify the root cause of this issue and if is something on `vim-prettier` itself fix it before `1.0` otherwise will submit a PR to `prettier` itself to fix this.

Thank you everyone for reporting issues and helping us making `prettier` and `vim-prettier` more and more stable

**Comment by Luobata** [comment] 2018-04-09 05:48
Hi @mitermayer ,

Here I make a file when I use :PrettierAsync it will crash. 
[c.js.zip](https://github.com/prettier/vim-prettier/files/1888575/c.js.zip)

**Comment by simianarmy** [comment] 2018-04-17 17:41
Same issue with me:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2018 07:37:16)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc

**Comment by mitermayer** [comment] 2018-05-07 15:09
Just to give everyone watching this issue an update, we will be working on making sure we either find a solution in `vim-prettier` itself or `prettier` for this issue prior to the `vim-prettier` 1.x release

**Comment by mitermayer** [comment] 2018-05-16 16:52
This is a duplicate of https://github.com/prettier/vim-prettier/issues/135, will be solving it on the #135

**Closed by mitermayer** 2018-05-16 16:52 UTC
Labels: triage

**Comment by mitermayer** [comment] 2018-05-16 17:16
Hi guys, Trying to debug this issue without being able to reproduce it yet. Will try to see if I can get a Mac with same version to see if that could be related.

In the meantime can you guys try reproducing this after adding this to your `~/.vimrc`

```viml
let g:prettier#autoformat = 0
```
cc @nerfologist , @radical-edo , @luobata, @simianarmy,

**Comment by mitermayer** [comment] 2018-05-16 17:18
cc @playahater
