### ISSUE TITLE
Error when running :Prettier on gvim

### ISSUE THREAD

**Issue by romch007** [prettier/vim-prettier#240] opened 2020-05-02 13:44 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current/expected behavior?**

I try to parse a js file with `:Prettier`

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

`1.0.0-alpha`

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

The command `:PrettierCliVersion` gives me no result. But with `prettier -v` in Git Bash I have `2.0.5`

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

It just returns `prettier`

**Did this work in previous versions of vim-prettier and/or prettier ?**

No, this is the first time I install the extension.

When I run `:Prettier` I have the error `Prettier: failed to parse buffer`. It quickly opens a window that almost instantly closes, but I managed to take a screenshot : 
![image](https://user-images.githubusercontent.com/38137329/80865695-56a1ab80-8c8b-11ea-8526-46ea59b6fadc.png)
My `.vimrc` config : 
```vim
call plug#begin('~/.vim/plugged')
Plug 'prettier/vim-prettier', {
  \ 'do': 'npm install',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html'] }
call plug#end()
nmap <Leader>p <Plug>(Prettier)
let g:prettier#config#single_quote = 'false'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#arrow_parens = 'avoid'
let g:prettier#config#parser = 'babylon'
```
I'm on Windows 10.

**Comment by mitermayer** [comment] 2020-05-13 00:59
Sorry, this is a duplicate of adding support to `prettier 2.0`

**Comment by mitermayer** [comment] 2020-05-13 00:59
Will try to work on that issue during the weekend

**Comment by mitermayer** [comment] 2020-05-13 00:59
Duplicate of https://github.com/prettier/vim-prettier/issues/232

**Closed by mitermayer** 2020-05-13 00:59 UTC
