### ISSUE TITLE
/* prettier-ignore */ inside CSS file not working

### ISSUE THREAD

**Issue by timonson** [prettier/vim-prettier#227] opened 2020-02-20 21:58 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**

I try to run the command `Prettier` on the following code inside a `.css` file:

```css
/* prettier-ignore */
#sub-slogan {
  font-family:${opts.font || "brandon"},sans-serif;
  font-size: 1.25rem;
  font-weight: 400;
  color: #9babb4;
  text-align: center;
  line-height: 1.5;
  width: 100%;
  margin: auto;
}
```

Current behavior: `Prettier: failed to parse buffer`

Expected behavior: `Prettier` works while ignoring this rule set.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

1.19.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

I am not sure

**Comment by mitermayer** [comment] 2020-03-22 09:36
The problem with the above is that `prettier` CLI itself can't parse that snippet. 

having `/* prettier-ignore */` only means skip formatting the following statement, but the problem is that `prettier` CLI cannot parse the file itself due to the line `  font-family:${opts.font || "brandon"},sans-serif;`

Closing this now as it's an issue with `prettier` cli and not `vim-prettier`

**Closed by mitermayer** 2020-03-22 09:36 UTC
