### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by trungdq88** [prettier/vim-prettier#82] opened 2017-12-03 05:00 UTC
0.8s is really slow for me. Is this normal?

![tmux_new_-s___basename___pwd____tmux_](https://user-images.githubusercontent.com/4214509/33522526-8ae21d10-d821-11e7-90fc-062ce640a82b.png)

The file only has 3 lines:

![image](https://user-images.githubusercontent.com/4214509/33522542-d2a2e08a-d821-11e7-8657-b6cb9b05534d.png)

Running in command line mode take 0.39s:
![tmux_new_-s___basename___pwd____tmux_](https://user-images.githubusercontent.com/4214509/33522562-32233d98-d822-11e7-89ea-d212f5217161.png)

So I guess there is not much we can do?

**Comment by mitermayer** [comment] 2017-12-03 08:37
Hi @trungdq88, 

Thanks for raising that, the reason why it may seem slower is that the command you are comparing it to is not the same command that `vim-prettier` executes over `prettier` you can see it in here (https://github.com/prettier/vim-prettier/blob/master/autoload/prettier.vim#L240).

Could you try running the same command on the command line ? intead of your example `prettier --write app.js` try:

```
cat app.js | prettier --print-width 80 --tab-width 2 --use-tabs false --semi true --single-quote true --bracket-spacing false --jsx-bracket-same-line true --trailing-comma all --parser flow --config-precedence prefer-file --stdin-filepath app.js --stdin
```

I have a feeling what is causing it to be slow will be some of the arguments passed to prettier itself, probably either `--stdin-filepath` or `--config-precedence`.

Please note you can also test this assumption by calling prettier CLI from vim directly and profiling that like:

```viml
:PrettierCli --write app.js
```

Will close this issue now but please comment in here your findings and if that is something related to `vim-prettier` itself I will make sure to work into fixing it. If its realted to `prettier` itself I may also be able to contribute a fix back to `prettier`.

Once again thank you for reporting this issue and looking forward to know a bit more about your findings!

**Closed by mitermayer** 2017-12-03 08:37 UTC

**Comment by mitermayer** [comment] 2017-12-03 08:41
I have also just tested it locally and confirmed this is `prettier` related.

Check this:

```
mitermayer@primus ~/temp $ time cat app.js | prettier --print-width 80 --tab-width 2 --use-tabs false --semi true --single-quote true --bracket-spacing false --jsx-bracket-same-line true --trailing-comma all --parser flow --config-precedence prefer-file --stdin-filepath app.js --stdin
const a = 1;

real	0m1.150s
user	0m1.055s
sys	0m0.113s
```

compared to:

```
mitermayer@primus ~/temp $ time prettier app.js 
const a = 1;

real	0m1.081s
user	0m1.014s
sys	0m0.070s
```

I don't have time right now to dig in on what exactly from that command is causing prettier to behave slower, but if you can find it out I should be able to then work on something  `prettier` main repo itself to mitigate it

**Comment by mitermayer** [comment] 2017-12-03 08:45
Also worth testing this out with different versions of `prettier` as this could also be some performance regressions by `prettier` itself creating new features

**Comment by trungdq88** [comment] 2017-12-03 10:27
`prettier` reported the task took, 44ms. But the actual `time prettier app.js` took ~1s. This is migt have something to do with the "bootstrap time" of `prettier`.

Is it possible to run something like an "daemon" or "prettier server" to "bootstrap" prettier only once?

**Comment by trungdq88** [comment] 2017-12-03 10:27
I will create a issue on `prettier` as well.
