### ISSUE TITLE
Unable to disable 'single-quote'

### ISSUE THREAD

**Issue by CGamesPlay** [prettier/vim-prettier#32] opened 2017-07-31 21:39 UTC
Prettier 1.5.3 does not accept `--single-quote false` as a way to using double quotes. This means that `g:prettier#config#single_quote = 'false'` doesn't work. I have to use this, which is icky: `g:prettier#config#single_quote = '--no-single-quote'`.

**Comment by mitermayer** [comment] 2017-08-02 18:03
Thanks for reporting this, will look into it and do a release ASAP, otherwise also accepting PR

**Comment by mitermayer** [comment] 2017-08-02 19:51
@CGamesPlay Will do a new release in the next day or two to fix this

**Comment by mitermayer** [comment] 2017-08-03 18:12
@CGamesPlay I am unable to reproduce this bug, can you please help me understand how is that happening to you?

Steps I have done to try to reproduce this bug (using prettier 1.5.2 and 1.5.3):

1. added this line to my `.vimrc`:

```vim
g:prettier#config#single_quote = 'false' 
```

2. created a dummy file (`foo.js`) with this contents:

```javascript
const a = 'foo';
```
3. Open `foo.js` with vim then run `:Pretter` 

From doing the above I got the same result both times:

```javascript
const a = "foo";
```

***

Would be great if you could provide me some more information on how to reproduce this error

**Comment by mitermayer** [comment] 2017-08-05 07:18
@CGamesPlay Will be closing this issue since I can't reproduce it. Feel free to re-open it if you can provide more information on how to reproduce it.

thank you for reporting it :)

**Closed by mitermayer** 2017-08-05 07:18 UTC
Labels: bug

**Comment by CGamesPlay** [comment] 2017-08-06 19:38
No worries. I'll collect my versions and try again. It's possible I wasn't setting the variables correctly? Will double check and report back if necessary.
