### ISSUE TITLE
Bug: failed to parse buffer. 

### ISSUE THREAD

**Issue by kyle-dormer** [prettier/vim-prettier#214] opened 2019-10-26 15:24 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current/expected behavior?**
Prettier cannot format the file due to `Prettier: failed to parse buffer.` This occurs both on save and when executing the `:Prettier` and `PrettierAsync` commands manually. The same error occurs on both macvim and neovim. 

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.18.2

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
Previously worked on neovim, not working on macvim. However, the last time it was used was months ago and I can't give a specific version that it worked under. 

This is off of a clean prettier install. I don't know if it would be due to other plugins but below are the plugins I have enabled:
```
" Plug
  1 call plug#begin('~/.vim/plugged')
  2   Plug 'Valloric/YouCompleteMe'
  3   Plug 'altercation/vim-colors-solarized'
  4   Plug 'scrooloose/nerdtree'
  5   Plug 'junegunn/goyo.vim'
  6   Plug 'nvie/vim-flake8', {'for': 'python'}
  7   Plug 'jiangmiao/auto-pairs', {'for': ['python', 'html', 'css']}
  8   Plug 'vimwiki/vimwiki'
  9   Plug 'suan/vim-instant-markdown', {'for': 'markdown'}
 10   Plug 'mattn/emmet-vim'
 11   Plug 'prettier/vim-prettier', {
 12   \ 'do': 'yarn install',
 13   \ 'branch': 'release/1.x',
 14   \ 'for': [
 15     \ 'javascript',
 16     \ 'typescript',
 17     \ 'css',
 18     \ 'less',
 19     \ 'scss',
 20     \ 'json',
 21     \ 'graphql',
 22     \ 'markdown',
 23     \ 'vue',
 24     \ 'lua',
 25     \ 'php',
 26     \ 'python',
 27     \ 'ruby',
 28     \ 'html',
 29     \ 'swift' ] }
 30 call plug#end()
```

**Comment by geoyws** [comment] 2019-10-28 12:00
I have this same problem. Maybe it's because I updated to a later version. Anyone else getting "failed to parse buffer"?

**Comment by agaryen** [comment] 2019-11-02 16:05
Same here. It seems to be quite a recurring issue, according to the number of github issues regarding this specific error.

**Comment by markplindsay** [comment] 2019-11-09 00:46
Stepping back to prettier@1.18.2 fixed it for me with vim-prettier 0.2.7.

I thought this was weird since the OP reported they were using 1.18.2. So, to make sure it wasn't something unrelated, I double checked by reinstalling 1.19.0. Got the error. Downgraded to 1.18.2. No more error.

**Comment by daern91** [comment] 2019-12-16 14:47
For what it's worth, I'm also seeing issues with prettier version `1.19.0` but downgrading to `1.18.x` makes everything work fine again.

**Comment by aca** [comment] 2019-12-23 03:29
```
function Foo(arg: any){
  console.log(arg as string)
}
```
failed to handle type conversion "arg as string" for tsx (vim prints filetype as typescriptreact)

but, cli works just fine.

**Comment by mitermayer** [comment] 2019-12-23 20:49
I am almost on leave from work, and will look at this issues from tomorrow :)

**Comment by koljakube** [comment] 2020-01-31 08:48
For what it's worth, I am having the same problem. It seems to be related to the file type.

I tried switching from `leafgarland/typescript-vim` and `peitalin/vim-jsx-typescript` to `sheerun/vim-polyglot`, and `vim-prettier` fails with the line "failed to parse buffer".

With the two previous plugins the filetype was typescript.tsx and everything worked, now it is typescriptreact and fails. For now I solved this by putting `au! BufNewFile,BufRead *.tsx setf typescript.tsx` into my [filetype.vim](https://vim.fandom.com/wiki/Filetype.vim). The filetype seems to get overwritten by some plugin, but it still works.

**Comment by mitermayer** [comment] 2020-02-02 22:18
Hi @koljakube,

Great finding, this explain a lot. I previously had removed the filetypes definition from the release/1.x branch due to relying on prettier itself to be capable of identifying the filetype based on extension. 

I will re-add that back and dig on upstream to understand what can be going wrong within the communication between vim-prettier and prettier itself

**Comment by mitermayer** [comment] 2020-02-13 11:43
I have reincluded file type definitions and branch 1.0 has been merged into master. Is anyone still facing this issues ?

Please comment/reopen this issue if you are still facing this issue

**Comment by ParamagicDev** [comment] 2020-02-15 13:24
Still encountering this issue. 

Neovim: 0.4.3
Prettier Version: 1.0.0-alpha
Prettier CLI version: 1.19.1
Prettier CLI Path: /home/krog/.vim/plugged/vim-prettier/node_modules/.bin/prettier
Node version: 11.15.0

**Comment by mitermayer** [comment] 2020-02-16 02:55
Thanks for including your config it is super helpful , I will investigate this issue with neovim and comment in here

**Comment by ParamagicDev** [comment] 2020-02-18 01:26
Let me know if there's any other way I can help. My full config is here:

[https://github.com/ParamagicDev/config-files/blob/master/dotfiles/vimrc](https://github.com/ParamagicDev/config-files/blob/master/dotfiles/vimrc)

I haven't tested whether it works in regular vim yet. I'll test it next time I'm at my computer. I'll also try removing plugins 1 by 1. Who knows, it could be a plug-in compatibility issues.

**Comment by ParamagicDev** [comment] 2020-02-18 03:07
So I found that the issue comes up specifically in this repository when editing `.js` files:

[https://github.com/ParamagicDev/ma-protocol-rewrite/tree/development](https://github.com/ParamagicDev/ma-protocol-rewrite/tree/development)

I've tried changing the default parser to Babylon and that did not fix the issue. I swapped over into one of my rails projects and did not encounter the issue with `.js` files.

My best guess is that `.prettierrc` file provided by Gatsby may be causing the error. I'm not 100% however.

**Comment by mitermayer** [comment] 2020-02-18 11:23
hi @ParamagicDev

Thank you for the snippet, I am able to reproduce this issue on my end! 

This bug seems to be something related to the `.prettierrc` in that repo, if i delete that file the `vim-prettier` works as expected. 

Will keep digging into it and comment in here any findings

**Comment by mitermayer** [comment] 2020-02-18 12:30
@ParamagicDev 

It looks like the problem is that one of `vim-prettier` dependencies `` is bringing a broken version of prettier CLI managed to fix this by updating the yarn lock file.

can you please try the following and see if you can still repro this error:

1. update vim-prettier to latest master (should contain this commit https://github.com/prettier/vim-prettier/commit/7041b9cb8bee84f432f1e168f826a90a0beea93a)
2. delete the existing `node_modules` from `~/.vim/plugged/vim-prettier`
3. do a `yarn install`

With the above i was no longer able to repro that issue

**Comment by ParamagicDev** [comment] 2020-02-19 03:25
@mitermayer Thank you so much for this. Everything's working as expected now.

**Comment by mitermayer** [comment] 2020-02-19 07:08
Closing this issue now, feel free to comment or reopen this issue if anyone experience same problem again

**Closed by mitermayer** 2020-02-19 07:08 UTC

**Comment by nratter** [comment] 2020-06-30 19:46
I'm still having issues with this. If I remove my .prettierrc.json file it works. It appears I have the commit posted above in my yarn.lock file. Any suggestions?

**Comment by kyle-dormer** [comment] 2020-07-02 08:38
@nratter Perhaps a syntax error with your `.prettierrc.json`? I can confirm the solution fixed my original problem but a syntax error with configuring Prettier caused it to reappear, fixed by re-examining the file.

**Comment by nratter** [comment] 2020-07-02 14:46
@kyle-dormer There were no syntax errors in my `.prettierrc.json` file. However, I was able to fix this by using `'branch': 'release/0.x'` in the vim-plug options.

**Comment by theycallmeswift** [comment] 2020-08-23 21:04
I can confirm that this bug is still live on the latest version of vim-prettier. The solution for me was to install both `leafgarland/typescript-vim` and `peitalin/vim-jsx-typescript`. This changed the filetype from `typescriptreact` to `typescript.tsx`

**Comment by ItsTarik** [comment] 2020-08-28 19:15
I don't know why this **PR** is `closed`, its very frustrating having this bug with the actual release ! what @mitermayer proposed solved my problem but I've lost some time ..

**Comment by theycallmeswift** [comment] 2020-08-29 22:25
Further, I have no determined that normal typescript files (`:set filetype?` returns `typescript`) do not trigger prettier on save either. I had to add the following workaround to my vimrc:

```
  autocmd BufRead,BufNewFile *.ts set filetype=typescript.tsx
```

**Comment by stumash** [comment] 2020-10-21 18:29
I also have this bug, newest vim-prettier. for some reason, when I switched to using prettier through coc-prettier instead of vim-prettier, everything worked just fine

**Comment by theycallmeswift** [comment] 2020-10-30 20:58
For future folks who discover this issue, I ended up switching to ale + prettier instead and it's working flawlessly.  Once you install Ale (I did it via Plug), you just add this to your .vimrc

```vim
  let g:ale_fix_on_save = 1
  let g:ale_fixers = {
  \   'javascript': ['prettier', 'eslint'],
  \   'typescript': ['prettier', 'eslint'],
  \}
```

**Comment by marcmarina** [comment] 2020-11-30 12:11
I still have this issue when I try to format manually with `:Prettier`

**Comment by jikkujose** [comment] 2021-11-29 10:09
I am still having this issue! Interestingly its not there for typescript files!

**Comment by nippyin** [comment] 2022-07-14 01:09
Me too still have issue and in my case json files are able to format just fine its Yaml file which gives this error Prettier: Failed to parse buffer (PrettierAsync)

**Comment by mattxyzeth** [comment] 2022-08-16 11:09
I was having this issue as well. My prettier config was formatted as JS using `module.exports`. I converted it to JSON and removed the file extension, and this seemed to have fixed the issue for me. The file name should be `.prettierrc`, and the format should be JSON.

**Comment by kevinw** [comment] 2022-09-01 11:34
Also seeing this issue with a fresh install and running `:Prettier`

**Comment by gosukiwi** [comment] 2022-09-16 22:15
> For future folks who discover this issue, I ended up switching to ale + prettier instead and it's working flawlessly. Once you install Ale (I did it via Plug), you just add this to your .vimrc
> 
> ```viml
>   let g:ale_fix_on_save = 1
>   let g:ale_fixers = {
>   \   'javascript': ['prettier', 'eslint'],
>   \   'typescript': ['prettier', 'eslint'],
>   \}
> ```

I was already using ALE, and that works great! Eslint is a bit slow but just leaving prettier is what I wanted anyways :) Thanks!

**Comment by sshh0** [comment] 2023-01-22 20:42
Was getting this error for files without an extension. Dissapeared after adding .js extention.
