### ISSUE TITLE
Unexpected token @

### ISSUE THREAD

**Issue by Luobata** [prettier/vim-prettier#109] opened 2018-01-31 14:19 UTC
The prettier throw a exception when use the `decorator`.
enviroment: js with babel-env.

**Comment by mitermayer** [comment] 2018-01-31 15:01
Hi @Luobata ,

Thank you for submitting this issue, in order for me to better assist / debug this problem could you please provide me some more info on:

the resolved prettier cli version:

```
:PrettierCliVersion
```

the prettier executable path:

```
:PrettierCliPath
```

vim prettier version

```
:PrettierVersion
```

***

Other information is the extension of the file you were editing while running that command.

thanks a lot!

**Comment by mitermayer** [comment] 2018-01-31 15:03
Could you also provide me the steps you did in other to encounter this issue ? Also does the prettier CLI for your project works on the file by ‘.node_modules/.bin/prettier yourfile’ ?

**Comment by mitermayer** [comment] 2018-01-31 16:20
Not sure whAt issue you may be facing but worth checking on prettier itself https://github.com/prettier/prettier/issues/759 in the past the flow parser had some issues with decorators

**Comment by nelsyeung** [comment] 2018-02-01 23:52
I just want to add that I'm having this problem as well:
```
:PrettierCliVersion
1.10.2

:PrettierCliPath
/Users/nelsyeung/Sites/test/Web\ App/node_modules/.bin/prettier

:PrettierVersion
0.2.6
```

Executing the executable itself works:
```
./node_modules/.bin/prettier --single-quote --trailing-comma es5 --write "{imports,tests,client,server}/**/*.{js,jsx}"
```
It works with passing in a single file as well.

**Comment by nelsyeung** [comment] 2018-02-02 00:29
@Luobata are you sure you want to use the flow parser which is the default in vim-prettier, but not the default in prettier?

It's likely that you want to add this to your `.vimrc`
```
let g:prettier#config#parser = 'babylon'
```

**Comment by mitermayer** [comment] 2018-02-03 17:43
I am closing this issue since I cannot reproduce and did not have enough information to do so, please feel free to comment or reopen this issue if you can add some more information around it

**Closed by mitermayer** 2018-02-03 17:43 UTC
Labels: triage

**Comment by Luobata** [comment] 2018-02-07 13:20
@nelsyeung 3q! It work and solve my problem.

**Comment by Luobata** [comment] 2018-02-07 13:22
@mitermayer thanks for your support and sorry not leave enough information, and the problem was resolved by add 
`let g:prettier#config#parser = 'babylon'`
