### ISSUE TITLE
Autoformatting Stops Working

### ISSUE THREAD

**Issue by nalanj** [prettier/vim-prettier#228] opened 2020-02-25 16:06 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current/expected behavior?**

Autoformat for some reason stops working randomly for me. Restarting vim seems to restore it to the expected behavior. I haven't noticed any patterns around when it stops working. I've had this happen maybe 2 or 3 times in the past few weeks.

I'm only using a couple of very basic config options:

```
let g:prettier#autoformat = 1 
let g:prettier#autoformat_require_pragma = 0
```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

1.19.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

I'm not completely sure due to the randomness of it not working.

**Comment by mitermayer** [comment] 2020-02-28 00:09
Hi there,

> I'm not completely sure due to the randomness of it not working.

Can you describe a bit around this randomness ?

>  I've had this happen maybe 2 or 3 times in the past few weeks.

Is that with files that was previously working ? Do you recall any actions done prior such as changing buffers or having split windows ?

Can you also maybe provide vim version ?

Would love to help looking into this issue

**Comment by nalanj** [comment] 2020-02-28 03:15
> Is that with files that was previously working ? Do you recall any actions done prior such as changing buffers or having split windows ?

It's definitely with files that were previously working. Typically I'll immediately check with `:Prettier` when I notice it didn't format and it will format, but the autoformatting will be disabled until I completely close vim. I'm not sure if it specifically relates to changing buffers or splitting windows, but I definitely do both of those things very frequently.

> Can you also maybe provide vim version ?

8.1.1401. It's the Debian packaged vim.

> Would love to help looking into this issue

Thanks! I'd love to help however I can, but I wasn't sure if there are any typical debugging steps from here.

**Comment by nalanj** [comment] 2020-02-29 12:19
So I switched to manually setting up an autocmd for it, and that seems to have resolved the issue (just in case anyone else hits this as well).

**Comment by mitermayer** [comment] 2020-03-21 12:33
Glad @nalanj was able to unblock himself, and apologies for not getting into this issue earlier. I have moved countries and now we are all facing this covid pandemic. 

Slowly catching up with issues in this repo and hopefuly will be resolving all of them soon

**Comment by mitermayer** [comment] 2020-03-22 09:34
Closing this for now as I tried to reproduce this locally without success. If anybody else is able to reproduce this and can supply some steps on how to do so I can reopen this issue and work on it again

**Closed by mitermayer** 2020-03-22 09:34 UTC

**Comment by gadkadosh** [comment] 2021-01-04 11:10
I have had this problem too and I now think it is related to the ftplugins vim-prettier ships. 
I'm not a vim expert, but it seems when vim-prettier loads the first time it declares autocmds for all supported file types. Then when I open a file for which an ftplugin (in vim-prettier) exists, if overrides the general autocmd (augroup Prettier) and I am left with an autocmd for just this single filetype, i.e. the last filetype to have been opened. Switching between hidden buffers (which is most of my vim workflow) does not lead to new autocmds being redeclared.
I'm not sure, but I feel like since we have the general autocmd, we don't need all of the ftplugin files. Does the parser need to be explicitly set for different filetypes? Doesn't prettier detect those automatically anyways?
