### ISSUE TITLE
Prettier throws an invalid expression ' --print-width ' when I run in vim

### ISSUE THREAD

**Issue by sachag678** [prettier/vim-prettier#143] opened 2018-06-15 16:03 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current/expected behavior?** Format the files but now it throws the following error when I run :Prettier ->
Error detected while processing function prettier#Prettier[8]..<SNR>48_Get_Prettier_Exec_Args:
line    3:
E15: Invalid expression: 
E15: Invalid expression: ' --print-width ' .

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?** 0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?** 1.13.5

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?** prettier

**Did this work in previous versions of vim-prettier and/or prettier ?** It was working before but not anymore. I'm not sure what changed. 

my.vimrc:

call plug#begin('~/.vim/plugged')

"Javascript plugins
Plug 'https://github.com/pangloss/vim-javascript.git'
Plug 'prettier/vim-prettier'

"Aethetics
Plug 'itchyny/lightline.vim'

call plug#end()

"Javascript plugins
"-------------------------------------------------------------------------------------
"pangloss
let g:javascript_plugin_jsdoc = 1

"Prettier
let g:prettier#autoformat = 0
"autocmd BufWritePre *.js Prettier

"Aesthetics
"-------------------------------------------------------------------------------------
"#Theme
"colorscheme minimalist
colorscheme afterglow
set number

"#Lightline
let g:lightline = { 'colorscheme': 'powerline', }
set laststatus=2
set noshowmode

"#Keyboard
set backspace=2

**Comment by mitermayer** [comment] 2018-06-15 16:30
Hi @sachag678,

In order for me to try to understand on how to better help you, could you please provide me a bit more information. 

* When did it stop working ? 
* What were the steps you done that made it stop working ? (upgraded prettier, installed new vim plugings, upgraded vim-prettier, run PlugUpdate, etc..)
* what is your OS ?

Could you please comment in this issue the output contents of:

```
vim --version
``` 

***

Probably not related, but do you mind updating the line on your `.vimrc` from:

```
Plug 'prettier/vim-prettier'
```

to:

```viml
Plug 'prettier/vim-prettier', { 'tag': '0.2.6' }
```

and remove your old `vim-prettier` directory by `rm -rf ~/.vim/plugged/vim-prettier` and installing again with plug within vim via running the command `:PlugInstall`


I just want try to understand if what may have broken your settings could be something done on the latest release

**Comment by sachag678** [comment] 2018-06-15 16:54
Hi, 

I am running vim - Vi Improved 8.1 - I installed this within the last 24 hours. Maybe this is the issue? 

I don't exactly remember if the issue popped up after or before this. 

I also removed the old vim-prettier and updated the tag to pull the 0.2.6 version. The issue still persists.

I am in ubuntu 16.04.4 LTS.

Maybe I should revert back to the older version of Vim?

**Comment by sachag678** [comment] 2018-06-15 16:55
I also downloaded and added a new colourscheme but I commented that out and tried running it again, but it didn't fix it.

**Comment by sachag678** [comment] 2018-06-15 17:00
I also had added in
`let g:prettier#config#print_width = 120`
into my .vimrc but removed it once the issue started. Again not sure if this cause the issue or not.

**Comment by mitermayer** [comment] 2018-06-15 17:13
Hi @sachag678,

I am not able to reproduce your issue. I also tried repro it on vim 8.1 without success.

**Comment by sachag678** [comment] 2018-06-15 17:48
thanks for trying! I will keep looking to try and figure it out.

**Comment by mitermayer** [comment] 2018-06-22 16:29
I will be closing this issue for now since I was unable to reproduce this issue and haven't seen this occurring to other users, but please feel free to re-open or comment in here if this seems to be happening to you

**Closed by mitermayer** 2018-06-22 16:29 UTC
