### ISSUE TITLE
no semicolon not working

### ISSUE THREAD

**Issue by nayed** [prettier/vim-prettier#83] opened 2017-12-07 14:11 UTC
```vim
Plug 'prettier/vim-prettier', { 
  \ 'do': 'npm install', 
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql'] }

let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.json,*.css,*.scss,*.less,*.graphql Prettier
let g:prettier#config#semi = 'false'
let g:prettier#config#trailing_comma = 'none'
```

Hi,
I've been using this config for some times and now in a fresh install it's printing semicolons. Did I missed something or something changed?

**Comment by nayed** [comment] 2017-12-07 14:26
I downgraded prettier from 1.9.1 to 1.8.2 and it's working again.
So the bug is from [prettier/prettier](https://github.com/prettier/prettier)?

**Comment by mitermayer** [comment] 2017-12-07 23:30
Hi @nayed,

Thanks for reporting this! Will have a look into it, there is a chance the new prettier version may have broken the integration. Will look into it ASAP prob

**Comment by mitermayer** [comment] 2017-12-08 21:36
Turns out this is a regression from prettier itself prettier/prettier#3432, will mitigate this problem now by disabling editorConfig compatibility until the next release of prettier where that gets fixed

Same as https://github.com/prettier/vim-prettier/issues/84

**Comment by mitermayer** [comment] 2017-12-08 21:44
fixed on https://github.com/prettier/vim-prettier/pull/85

**Closed by mitermayer** 2017-12-08 21:44 UTC
