### ISSUE TITLE
bash: no job control in this shell

### ISSUE THREAD

**Issue by AndreiMotinga** [prettier/vim-prettier#123] opened 2018-03-23 01:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug?

Just learned about prettier yesterday. Trying to install it in on neovim
Saving a file just adds  `bash: no job control in this shell`  to the top of the file without reindenting. 
Do I need to install any npm packages? Which ones? If so, please update docs because it's unclear.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.6

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
bash: no job control in this shell^@1.11.1^@

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`/Users/andrei/dev/crypto/node_modules/.bin/prettier`

**Comment by mitermayer** [comment] 2018-03-23 20:29
Hi @AndreiMotinga ,

Could you please provide me a bit more information in order for me be able to better assist you ?

* what is the version of neovim that you are running ? (output of `nvim --version | head -n 1`)
* what configuration for `vim-prettier` have you added to your `~/.config/nvim/init.vim` ?
* what is your OS ?

Thanks a lot!

**Comment by AndreiMotinga** [comment] 2018-03-23 23:18
Hey @mitermayer, sure thing. 

➜  ~ nvim --version | head -n 1
NVIM v0.2.0
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
➜  ~

in terms of vim-prettier config, I tried with and without settings. various things. Currently, I removed it. 

I tried to install it twice with no luck, so postponed it until weekend :) 

Thank you for your help. 
Cheers.

**Comment by mitermayer** [comment] 2018-03-25 04:30
No problem,

@AndreiMotinga  will close this issue for now as I could not reproduce it, if you run in this problem again feel free to reopen/comment with some steps on how to reproduce this and I will be happy to jump on it and try to aid you. 

Once again thank you for reporting this issue

**Closed by mitermayer** 2018-03-25 04:30 UTC
