### ISSUE TITLE
Ignoring unknown option --loglevel, --no-editorconfig and --config-precedence

### ISSUE THREAD

**Issue by ohcibi** [prettier/vim-prettier#89] opened 2017-12-11 14:30 UTC
Hi,

I've just setup again my vim/prettier/eslint setup and I noticed that when I use prettier with this plugin it adds (at least) 3 now unknown options to the prettier cli. I'm unsure if those options are just deprecated or replaced upstream as I didn't found anything in the changelogs. But it seems to work to just drop those options.

Heres what I did:
* Installed prettier in `node-6.9.5` locally with `package.json` (`npm install`)
* Opened a random js-file with some minor formatting issues
* Format with `<leader>p` (or by calling the Commands directly, I tried both actually)
* File now contains

```
Ignored unknown option: --config-precedence
Ignored unknown option: --no-editorconfig
Ignored unknown option: --loglevel
```

at the top.

**Comment by mitermayer** [comment] 2017-12-11 14:40
Hi @ohcibi  you are using `vim-prettier` with an older version of `prettier. Can you please check the output of:

1 - check your prettier executable path

```viml
:PrettierCliPath
```

2 - Check your prettier version

```viml
:PrettierVersion
```

You will need to update the `prettier` version for your project, most likely its an older version defined somewhere in an ancestor `package.json` file

**Comment by mitermayer** [comment] 2017-12-13 05:30
Closing this issue since it is probably due to using older prettier version. @ohcibi please feel free to comment/re-open if your problem is caused by a different issue

**Closed by mitermayer** 2017-12-13 05:30 UTC

**Comment by ohcibi** [comment] 2017-12-14 10:49
Yes you were right. Thanks!

**Comment by devth** [comment] 2018-01-16 21:44
It's not always possible to use the latest prettier. Can we have an option to not pass those args to the cli, or override the args passed?

My large-ish project is on prettier 1.7.4 and we can't upgrade at the moment.

**Comment by mitermayer** [comment] 2018-01-16 21:51
Hi @devth ,

It is pretty hard to keep `vim-prettier` backwards compatible with older versions of `prettier` specially the 1.7.4 where major changes has happened since.

You can always use an older version of `vim-prettier` by leveraging the `vim-plug`  'tag' directive:

```viml
Plug 'prettier/vim-prettier', { 'tag': '0.2.0' }
```

**Comment by devth** [comment] 2018-01-16 21:53
Oh, good call (duh, that's the point of versioning 🤪). Thanks, that worked!
